# Generated by Django 3.1.6 on 2021-02-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210208_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.categorypage'),
        ),
    ]
