# Generated by Django 3.1.6 on 2021-02-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productpage_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='name',
            field=models.CharField(default='shoes', max_length=250),
            preserve_default=False,
        ),
    ]
