# Generated by Django 3.1.6 on 2021-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210208_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
