# Generated by Django 3.1.6 on 2021-02-14 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('store', '0008_auto_20210208_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPage',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='CategoryPage',
            new_name='ProductCategory',
        ),
    ]
