# Generated by Django 3.1.6 on 2021-02-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('store', '0009_auto_20210214_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryIndexPage',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
