# Generated by Django 3.1.6 on 2021-02-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_book_bookauthor_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_authored', to='store.person'),
        ),
    ]
