# Generated by Django 3.1.6 on 2021-02-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productindex_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('color', models.CharField(choices=[('Grey', 'Grey'), ('Black', 'Black'), ('White', 'White'), ('Light Blue', 'Light Blue')], default='Black', max_length=25)),
                ('memory', models.CharField(choices=[('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], default='4GB', max_length=5)),
                ('hasSSD', models.BooleanField(default=False)),
                ('ssd_storage', models.CharField(choices=[('None', 'None'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('4TB', '4TB')], default='None', max_length=5)),
                ('stock', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('store.product',),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='memory',
            field=models.CharField(choices=[('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB')], default='4GB', max_length=5),
        ),
    ]
